# Generated by Django 5.0.6 on 2024-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='images/profile/')),
                ('aboutme_pic', models.ImageField(null=True, upload_to='images/profile/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('cv', models.FileField(null=True, upload_to='files/')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
